import { v4 as uuidv4 } from "uuid";

export const pizzaMenuList = [
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/6mVB3xq/prosciutto-e-funghi-pizza-min.jpg",
    imageThumbnail:
      "https://i.ibb.co/80TcWpQ/prosciutto-e-funghi-pizza-min.jpg",
    imageAlt: "prosciutto-e-funghi-pizza",
    title: "Prosciutto e funghi pizza",
    ingredient:
      "tomato sauce, mozzarella, thin slices of prosciutto cotto, and mushrooms",
    price: [
      { id: uuidv4(), size: "Small", price: 10, },
      { id: uuidv4(), size: "Medium", price: 13, },
      { id: uuidv4(), size: "Big", price: 15, },
    ],
    reviewCount: 4,
    rating: 4,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/PNrKzR5/Garlic-Fingers-min.jpg",
    imageThumbnail: "https://i.ibb.co/BtfbKmg/Garlic-Fingers-min.jpg",
    imageAlt: "Garlic-Fingers",
    title: "Garlic Fingers",
    ingredient: "cheese, dill, garlic, bacon, parsley",
    price: [
      { id: uuidv4(), size: "Small", price: 8 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 14 },
    ],
    reviewCount: 5,
    rating: 3,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/r54Nqgd/Detroit-Style-Pizza-min.jpg",
    imageThumbnail: "https://i.ibb.co/tY8FnSL/Detroit-Style-Pizza-min.jpg",
    imageAlt: "Detroit-Style-Pizza",
    title: "Detroit-Style Pizza",
    ingredient: "tomato sauce, pepperoni, mozzarella",
    price: [
      { id: uuidv4(), size: "Small", price: 10 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 15 },
    ],
    reviewCount: 15,
    rating: 4,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/SnhJJ76/Pizza-ortolana-min.jpg",
    imageThumbnail: "https://i.ibb.co/XshVVkW/Pizza-ortolana-min.jpg",
    imageAlt: "Pizza-ortolana",
    title: "Pizza ortolana",
    ingredient:
      "tomato sauce, olive oil, basil, mozzarella, eggplant, zucchini",
    price: [
      { id: uuidv4(), size: "Small", price: 11 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 16 },
    ],
    reviewCount: 20,
    rating: 4,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/T0TbGb0/Pizza-e-fichi-min.jpg",
    imageThumbnail: "https://i.ibb.co/GMJtDtM/Pizza-e-fichi-min.jpg",
    imageAlt: "Pizza-e-fichi",
    title: "Pizza e fichi",
    ingredient: "figs, mozzarella, olive oil, rosemary, garlic",
    price: [
      { id: uuidv4(), size: "Small", price: 9 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 14 },
    ],
    reviewCount: 35,
    rating: 5,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/mqCSbgB/Apizza-min.jpg",
    imageThumbnail: "https://i.ibb.co/1qfb7jn/Apizza-min.jpg",
    imageAlt: "Apizza",
    title: "Apizza",
    ingredient: "cheese, tomato, anchovy, garlic, oregano, olive oil",
    price: [
      { id: uuidv4(), size: "Small", price: 13 },
      { id: uuidv4(), size: "Medium", price: 15 },
      { id: uuidv4(), size: "Big", price: 17 },
    ],
    reviewCount: 40,
    rating: 4,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/CPw3m5Y/Pizza-rustica-min.jpg",
    imageThumbnail: "https://i.ibb.co/kmGs5gw/Pizza-rustica-min.jpg",
    imageAlt: "Pizza-rustica",
    title: "Pizza rustica",
    ingredient:
      "salsiccia, prosciutto cotto, prosciutto crudo, eggs, mozzarella, ricotta, pecorino romano, parmigiano reggiano",
    price: [
      { id: uuidv4(), size: "Small", price: 15 },
      { id: uuidv4(), size: "Medium", price: 17 },
      { id: uuidv4(), size: "Big", price: 19 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/v1qG1VF/Pizza-pesto-Genovese-min.jpg",
    imageThumbnail: "https://i.ibb.co/CB8ZBmc/Pizza-pesto-Genovese-min.jpg",
    imageAlt: "Pizza-pesto-Genovese",
    title: "Pizza pesto Genovese",
    ingredient: "pesto Genovese, mozzarella, olive oil",
    price: [
      { id: uuidv4(), size: "Small", price: 8 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 14 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/KKhCs99/Fugazza-min.jpg",
    imageThumbnail: "https://i.ibb.co/xFLVgMM/Fugazza-min.jpg",
    imageAlt: "Fugazza",
    title: "Fugazza",
    ingredient: "onion, olives, artichoke, parmigiano reggiano",
    price: [
      { id: uuidv4(), size: "Small", price: 9 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 14 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/yXmyxv7/Pizza-fiori-di-zucca-min.jpg",
    imageThumbnail: "https://i.ibb.co/R9G0Jrd/Pizza-fiori-di-zucca-min.jpg",
    imageAlt: "Pizza-fiori-di-zucca",
    title: "Pizza fiori di zucca",
    ingredient:
      "zucchini, anchovy, mozzarella, olive oil, black pepper, garlic",
    price: [
      { id: uuidv4(), size: "Small", price: 10 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 15 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/ZB38QVF/Pugliese-Pizza-min.jpg",
    imageThumbnail: "https://i.ibb.co/GWX2Z08/Pugliese-Pizza-min.jpg",
    imageAlt: "Pugliese-Pizza",
    title: "Pugliese Pizza",
    ingredient: "tomato sauce, mozzarella, pecorino romano, onion",
    price: [
      { id: uuidv4(), size: "Small", price: 9 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 15 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/CKPX6mM/Pizza-vegetariana-min.jpg",
    imageThumbnail: "https://i.ibb.co/yF4MpdY/Pizza-vegetariana-min.jpg",
    imageAlt: "Pizza-vegetariana",
    title: "Pizza vegetariana",
    ingredient: "tomato sauce, zucchini, eggplant, pepper, mozzarella",
    price: [
      { id: uuidv4(), size: "Small", price: 8 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 14 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/QJ8yYrV/Pizza-carbonara-min.jpg",
    imageThumbnail: "https://i.ibb.co/j8Vn3gY/Pizza-carbonara-min.jpg",
    imageAlt: "Pizza-carbonara",
    title: "Pizza carbonara",
    ingredient:
      "tomato sauce, panceta, grana padano, pecorino romano, mozzarella, parsley, eggs",
    price: [
      { id: uuidv4(), size: "Small", price: 11 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 16 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/hBR6QLh/California-Style-Pizza-min.jpg",
    imageThumbnail: "https://i.ibb.co/X7ZQ0jN/California-Style-Pizza-min.jpg",
    imageAlt: "California-Style-Pizza",
    title: "California-Style Pizza",
    ingredient: "shrimp, asparagus, seafood, peneapple",
    price: [
      { id: uuidv4(), size: "Small", price: 10 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 16 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/h9Y8RQ3/Pizza-alla-diavola-min.jpg",
    imageThumbnail: "https://i.ibb.co/PjDCZXq/Pizza-alla-diavola-min.jpg",
    imageAlt: "Pizza-alla-diavola",
    title: "Pizza alla diavola",
    ingredient: "tomato sauce, spicy salami, hot peppers, mozzarella, olives",
    price: [
      { id: uuidv4(), size: "Small", price: 12 },
      { id: uuidv4(), size: "Medium", price: 15 },
      { id: uuidv4(), size: "Big", price: 17 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/31vWGp5/Quattro-stagioni-pizza-min.jpg",
    imageThumbnail: "https://i.ibb.co/Tc1Rp4D/Quattro-stagioni-pizza-min.jpg",
    imageAlt: "Quattro-stagioni-pizza",
    title: "Quattro stagioni pizza",
    ingredient:
      "tomato sauce, prosciutto cotto, mozzarella, mushrooms, artichokes, ham",
    price: [
      { id: uuidv4(), size: "Small", price: 11 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 16 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/zRVtCnk/Pizza-ai-frutti-di-mare-min.jpg",
    imageThumbnail: "https://i.ibb.co/3NmPVrJ/Pizza-ai-frutti-di-mare-min.jpg",
    imageAlt: "Pizza-ai-frutti-di-mare",
    title: "Pizza ai frutti di mare",
    ingredient: "tomato sauce, shrimp, squid, mussels, olive oil",
    price: [
      { id: uuidv4(), size: "Small", price: 10 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 15 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/qB9pd6g/Stromboli-min.jpg",
    imageThumbnail: "https://i.ibb.co/VVDTt6C/Stromboli-min.jpg",
    imageAlt: "Stromboli",
    title: "Stromboli",
    ingredient: "mozzarella, pepperoni, capocollo, bresaola, salami",
    price: [
      { id: uuidv4(), size: "Small", price: 9 },
      { id: uuidv4(), size: "Medium", price: 12 },
      { id: uuidv4(), size: "Big", price: 15 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/cLfRFZs/Hawaiian-Pizza-min.jpg",
    imageThumbnail: "https://i.ibb.co/TLjJ87N/Hawaiian-Pizza-min.jpg",
    imageAlt: "Hawaiian-Pizza",
    title: "Hawaiian Pizza",
    ingredient: "tomato sauce, mozzarella, pineapple, ham",
    price: [
      { id: uuidv4(), size: "Small", price: 10 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 16 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/dWtKrZD/Calzone-Pizza-min.jpg",
    imageThumbnail: "https://i.ibb.co/Gx9P0mR/Calzone-Pizza-min.jpg",
    imageAlt: "Calzone-Pizza",
    title: "Calzone Pizza",
    ingredient: "tomato, mozzarella, lard, salame napoli, pork rinds, ricotta",
    price: [
      { id: uuidv4(), size: "Small", price: 12 },
      { id: uuidv4(), size: "Medium", price: 15 },
      { id: uuidv4(), size: "Big", price: 17 },
    ],
    reviewCount: 0,
    rating: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://i.ibb.co/f0BvNCp/Pizza-Napoletana-min.jpg",
    imageThumbnail: "https://i.ibb.co/Jk0Qpz7/Pizza-Napoletana-min.jpg",
    imageAlt: "Pizza-Napoletana",
    title: "Pizza Napoletana",
    ingredient: "tomato, mozzarella, basil, olive oil, oregano, yeast",
    price: [
      { id: uuidv4(), size: "Small", price: 10 },
      { id: uuidv4(), size: "Medium", price: 13 },
      { id: uuidv4(), size: "Big", price: 16 },
    ],
    reviewCount: 0,
    rating: 1,
  },
];
